### ISSUE TITLE
Mình test còn 1 số lỗi sau

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-photos#10]
Phần thể hiện chủ đề theo dạng lưới còn lỗi CSS . Và đưa chuột vào cái hình thì không có tác dụng, phải lick chuột vào tiêu đề album nó mới chạy
![1](https://cloud.githubusercontent.com/assets/10916826/10038362/0868c29e-61ef-11e5-9c0e-3fc04a35e291.png)

2 block album mới và album theo chủ đề khi lick vào bị lỗi đường dẫn. Hình như thiếu phần chủ đề,  nó có dạng
http://te6nweb.com/photos//tenalbum.html

Góp ý, Giới hạn text cái tiêu đề album trong block album cùng chủ đề, vì kg giới hạn để cái dài cái ngắn nhìn xấu :)) 

![2](https://cloud.githubusercontent.com/assets/10916826/10038402/b8d80072-61ef-11e5-8a7a-9831a80e2124.png)

Phần block album mới có thể thêm thông tin như cái block detail như kiểu mẫu, địa điểm chụp... vì cái hình thì to, cái tiêu đề thì nhỏ nên nó trống nhìn cũng .... xấu  :)))

![3](https://cloud.githubusercontent.com/assets/10916826/10038509/3bd3774e-61f1-11e5-926d-1f05e815b3e7.png)

Đang test tiếp ....

**Comment by anhyeuviolet** [comment]
Fixed
https://github.com/anhyeuviolet/module_photos/commit/42ce1faf2740bdfc06f0e85a76dc3a223deb0221
