### ISSUE TITLE
Tạo mới một album ảnh

### ISSUE THREAD

**Issue by hpleduit** [anhyeuviolet/module-photos#11]
Cảm ơn bạn đã chia sẽ album này mình đã test thử có một số chổ bất cập như sau:
- Khi tạo mới một album ảnh ở phần Thư mục chứa ảnh sao không tự động tạo được giống như chổ phần Liên kết tĩnh chỉ cần nhấn nút refresh ở bên là tạo ngay đường dẫn, ở phần Tạo thư mục chứa ảnh ta cũng làm vậy thì OK hơn.
- Phần Thẻ Meta title ta cũng chỉ cần mặc định lấy thông tin từ tên album ảnh là OK, còn người nhập có thể nhập thêm hay xoá tuỳ ý....
- Còn một số block ảnh ngoài site vẫn chưa hoàn chỉnh mong bạn sớm hoàn thiện tốt để module ngày tốt hơn

**Comment by anhyeuviolet** [comment]
Fix through
https://github.com/anhyeuviolet/module_photos/commit/cde902888a37f12753d1e0d776cb8b1c062ccf00
and
https://github.com/anhyeuviolet/module_photos/commit/ac182ed7ac54bec5f6c67e8dbb56604dc90dc2b0
