### ISSUE TITLE
Help thêm trường "Người đăng" vào CSDL

### ISSUE THREAD

**Issue by hoanglongvnpt** [anhyeuviolet/module-photos#15]
Bạn:  - Hướng dẫn thêm 1 trường người đăng vào csdl và xuất ra file tpl cho mình với nha. 
- Thêm chức năng hover vào albums khi rê chuột sẽ xuất hiện các nút share mạng xã hội.
  Albums đang test và cảm thấy khá ổn. Thank bạn!

**Comment by anhyeuviolet** [comment]
https://github.com/anhyeuviolet/module_photos/commit/18cfd6b35b93fc2208650c58d66bc0e092288b5d
