### ISSUE TITLE
Đề xuất thêm chức năng

### ISSUE THREAD

**Issue by thanhvu7411** [anhyeuviolet/module-photos#18]
Modules Photo rất hay nhưng theo ý mình nên thêm phần giới thiệu cho ảnh (như caption trên ảnh facebook).
Phần nội dung này nên cho phép edit đầy đủ.

**Comment by anhyeuviolet** [comment]
Cái này thực ra là có rồi, nhưng nó nhúng trong chỉnh sửa Album.
Chắc mình sẽ làm cái hướng dẫn sơ để chỉnh sửa cái này, cũng như hiện caption ra trang chủ. Sau này có thời gian sẽ tách phần chỉnh sửa từng ảnh con ra sau.

**Comment by anhyeuviolet** [comment]
Display image caption (description)

https://github.com/anhyeuviolet/module_photos/commit/987edf69e3504c50bf160f47e5ac059e466ec078

**Comment by anhyeuviolet** [comment]
https://github.com/anhyeuviolet/module-photos/releases/tag/1.3.11
