### ISSUE TITLE
Góp ý nhỏ để Module được tốt

### ISSUE THREAD

**Issue by hoanglongvnpt** [anhyeuviolet/module-photos#3]
Mình vừa test trên localhost, có một số lỗi như sau.
1) 3 block không chạy được cái nào.
2) Phần thể hiện album ngoài trang chủ còn lộn xộn, chưa có CSS
3) Phần xem album : Dạng xem lightbox (hiệu ứng blueimp) hoặc xem từng ảnh con có vẻ như load chậm, khi được khi không, có khi lick vào xem hình nó không hiện ra lightbox mà ra cái link của ảnh gốc trên thư mục upload.... đang test tiếp

**Comment by anhyeuviolet** [comment]
Fixed.
- Phần thể hiện album ngoài trang chủ còn lộn xộn, chưa có CSS
  https://github.com/anhyeuviolet/module_photos/commit/5c2027b8c5d5f2e9f723768628bc65c1bd71b2f9
- 3 block không chạy được cái nào.
  https://github.com/anhyeuviolet/module_photos/commit/0a32fd7f65e0c9a496b0f23f029caf20afd6315c
- Phần xem album : Dạng xem lightbox (hiệu ứng blueimp) hoặc xem từng ảnh con có vẻ như load chậm, khi được khi không, có khi lick vào xem hình nó không hiện ra lightbox mà ra cái link của ảnh gốc trên thư mục upload
  https://github.com/anhyeuviolet/module_photos/commit/ce4132d9a2f64ce8cbac81812bc715b2ce248bba
