### ISSUE TITLE
Còn nhiều đường dẫn upload sử dụng $module_name

### ISSUE THREAD

**Issue by mynukeviet** [anhyeuviolet/module-photos#33]
https://github.com/anhyeuviolet/module-photos/blob/develop/modules/photos/admin/main.php#L158
Trong đây còn nhiều chổ đường dẫn thư mục uploads dùng `$module_name`, dùng `$module_upload` mới đúng.

**Comment by anhyeuviolet** [comment]
https://github.com/anhyeuviolet/module-photos/commit/43084277a47c4863624c4fcb43d1f5f46cbe8416
