### ISSUE TITLE
Đề xuất: Cho phép lấy nguồn album từ photos google hoặc onedrive

### ISSUE THREAD

**Issue by quangcuong** [anhyeuviolet/module-photos#36]
- Thứ nhất: Đỡ tốn dung lượng lưu trữ trên host
- Thứ hai: khi backup web cũng nhẹ hơn

**Comment by anhyeuviolet** [comment]
:dancer: Bạn có tính tới mình viết không nổi chưa ?

**Comment by quangcuong** [comment]
iHì hì! Hy vọng trong tương lai sẽ có. Trước mắt chờ bản update để chạy được trên nukeviet final đã!
(Mình không biết về lập trình, nhưng đang cố gắng tìm hiểu. Hy vọng một ngày nào đó có thể làm được)

**Comment by mrbemp** [comment]
nếu mà lấy nguồn đc từ google photos hoặc link ngoài thì tốt quá.

**Comment by anhyeuviolet** [comment]
Google photos no longer support external API.
