### ISSUE TITLE
module photo khong hoat dong tren nukeviet 4 offical

### ISSUE THREAD

**Issue by trungtuan2** [anhyeuviolet/module-photos#37]

**Comment by trungtuan2** [comment]
bị lỗi " Lỗi xử lý giao diện
Lỗi, hệ thống không tồn tại giao diện, bạn cần liên hệ với quản trị site để sửa lại" nhờ ad kiểm tra lại dùm em cái được không"

**Comment by anhyeuviolet** [comment]
Tạm khắc phục : Vào cấu hình module Photos, phần Giao diện trang chủ (layout) chọn là Mặc định rồi lưu lại. Dọn dẹp hệ thống.

**Comment by trungtuan2** [comment]
Thank alot, nhung fai chon left-main-right thi moi hien thi dc

Get Outlook for Android

On Sat, May 21, 2016 at 6:34 AM -0700, "Kenny Nguyen" notifications@github.com wrote:

Tạm khắc phục : Vào cấu hình module Photos, phần Giao diện trang chủ (layout) chọn là Mặc định rồi lưu lại. Dọn dẹp hệ thống.

**Comment by anhyeuviolet** [comment]
https://github.com/anhyeuviolet/module-photos/releases/tag/1.3.11

**Comment by nguyengiakt** [comment]
đã fix đc, cảm ơn bạn, mình vào từng album chọn kiểu layout thì mới đc.
