### ISSUE TITLE
Lỗi, hệ thống không tồn tại giao diện, bạn cần liên hệ với quản trị site để sửa lại

### ISSUE THREAD

**Issue by nguyengiakt** [anhyeuviolet/module-photos#38]
Khi úp lên bản 4.0.29 thì click vào detail nó bị lỗi
Lỗi, hệ thống không tồn tại giao diện, bạn cần liên hệ với quản trị site để sửa lại
lỗi này có thể vào đâu sửa được bạn.
thks

**Comment by anhyeuviolet** [comment]
Bạn xem bên này
https://github.com/anhyeuviolet/module-photos/issues/37
