### ISSUE TITLE
Module Photos không tạo được album sau khi upgrade lên V4.1

### ISSUE THREAD

**Issue by lhanh1981** [anhyeuviolet/module-photos#39]
Sau khi mình upgrade lên V4.1 thì mỗi lần tạo album đều bị lỗi "504 gateway timeout". Có lẽ do thao tác với CSDL có chỗ nào chưa phù hợp khiến một số câu lệnh làm server bị quá tải chăng? Server version: 10.0.27-MariaDB - MariaDB Server

**Comment by anhyeuviolet** [comment]
@lhanh1981 cảm ơn bạn !
Mình thử nghiệm trên site demo thì không thấy lỗi như bạn nói.
https://nukeviet-hvt.rhcloud.com/videos/
