### ISSUE TITLE
Lỗi timeout khi upload nhiều file vào album cùng lúc

### ISSUE THREAD

**Issue by lhanh1981** [anhyeuviolet/module-photos#40]
Khi tạo và upload hình vào album, qua kiểm tra trên hosting thấy việc upload diễn ra rất nhanh, các file nhanh chóng được up lên thư mục data/tmp trên server (bao gồm cả file thumbs). Tuy nhiên, việc move uploaded files từ thư mục data/tmp sang thư mục upload/images và upload/thumbs tương ứng diễn ra rất chậm. Điều này khiến server không trả về thông tin trong thời gian dài, và website bị timeout.

Em có thể thấy điều đó khi refresh liên tục thư mục data/tmp sau khi upload, sẽ thấy các file được chuyển đi khác chậm chạp và khi bị timeout thì việc di chuyển này bị dừng. Điều này dẫn đến việc còn lại một đống file rác đã upload lên trong thư mục data/tmp chưa được chuyển về thư mục upload tương ứng.

Nhờ bạn kiểm tra lại giúp. Tks

**Comment by anhyeuviolet** [comment]
Vấn đề này còn phụ thuộc cấu hình server, dung lượng ảnh gốc, tốc độ đường truyền, số ảnh upload mỗi một lần.
Bạn có thể cung cấp thêm thông tin không ?

**Comment by lhanh1981** [comment]
Mình đã test trên hosting của Bạch Kim và 123hosting đều xảy ra lỗi tương tự. Mỗi lần upload khoảng 10 file là OK, còn upload khoảng 20 files trở lên là timeout. Mặc dù mỗi file chỉ khoảng 100k->300kb tổng dung lượng 20 files cũng chỉ khoảng vài MB. Mình cũng đã chỉnh lại chút trong cấu hình PHP để tăng thời gian xử lý lệnh trên hosting và liên hệ kỹ thuật của hosting nhưng vẫn chưa có giải pháp.

Cũng có thể do cấu hình hosting trong việc ưu tiên các tác vụ trên server. Bạn test thử trên hosting của bạn nếu mà cũng lỗi vậy có khi phải nghiên cứu việc tối ưu cái code upload. Việc upload lên hosting và tạo thumbs rất nhanh (xem trong data/tmp là rõ), nhưng việc chuyển về real upload folder thì lại chậm như rùa, khi timeout không chuyển kịp hết files về real upload thì còn tồn lại file trong data/tmp và không ghi được vào CSDL.

**Comment by anhyeuviolet** [comment]
Cảm ơn bạn !
Mình đã test trên khá nhiều mơi trường hosting.
Cá biệt website riêng của mình dùng module này, 1 album upload ko bao giờ dưới 20 ảnh nhưng ko vấn đề gì.

Hàm xử lý ảnh module này dùng là Class Image có sẵn của NukeViet.

```
new NukeViet\Files\Image( $filePath, NV_MAX_WIDTH, NV_MAX_HEIGHT );
```

Do đó cái này mình nghĩ bạn nên tìm 1 môi trường hosting nữa để thử nghiệm cho khách quan.

**Comment by lhanh1981** [comment]
Chào Anh,

Qua thời gia kiểm tra kỹ thuật xin trả lời Anh như sau ạ:
- Do việc upload các file lên vượt quá thời gian cho phép (120s) -> dẫn đến việc time out. do hosting dùng chung hệ thống với nhiều site khác nên không thể thay đổi thông số này, thông số này nằm dưới mức 120s sẽ đảm bảo website sẽ hạn chế việc bị tấn công ddos. (kỹ thuật sẽ xem xét thay đổi trong thời gian tới)
- Kỹ thuật cũng có thử cài đặt wordpress trên hosting thì việc upload file với số lượng lớn vẫn diễn ra hoàn tất --> do phần upload của Nuke Việt chưa được tối ưu phần này.

Vì vậy kỹ thuật xin tư vấn một số phương án như sau:
- Anh có thể tùy chỉnh lại số lượng file upload lên cùng lúc để tránh bị time out.
- Hoặc Anh có thể tham khảo phương án dùng VPS để có thể chủ động thay đổi các thông số kỹ thuật hỗ trợ cho website ạ. Nếu Anh có nhu cầu dùng thử VPS vui lòng phản hồi kỹ thuật sẽ liên hệ kinh doanh hỗ trợ Anh sử dụng thử VPS trong thời gian tới nhé. Xin cảm ơn!

Trân trọng,

Trên đây là thư kỹ thuật trả lời mình. Mình sẽ xem lại code và test thêm trên hosting khác xem sao. Tks bạn.

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Kenny Nguyen notifications@github.com Date: 10/18/16  07:36  (GMT+07:00) To: anhyeuviolet/module-photos module-photos@noreply.github.com Cc: Lê Hoàng Anh lhanh1981@gmail.com, Author author@noreply.github.com Subject: Re: [anhyeuviolet/module-photos] Lỗi timeout khi upload nhiều file vào album cùng lúc (#40) 
Cảm ơn bạn !

Mình đã test trên khá nhiều mơi trường hosting.

Cá biệt website riêng của mình dùng module này, 1 album upload ko bao giờ dưới 20 ảnh nhưng ko vấn đề gì.

Hàm xử lý ảnh module này dùng là Class Image có sẵn của NukeViet.

new NukeViet\Files\Image( $filePath, NV_MAX_WIDTH, NV_MAX_HEIGHT );

Do đó cái này mình nghĩ bạn nên tìm 1 môi trường hosting nữa để thử nghiệm cho khách quan.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anhyeuviolet/module-photos","title":"anhyeuviolet/module-photos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/anhyeuviolet/module-photos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anhyeuviolet in #40: Cảm ơn bạn !\r\nMình đã test trên khá nhiều mơi trường hosting.\r\nCá biệt website riêng của mình dùng module này, 1 album upload ko bao giờ dưới 20 ảnh nhưng ko vấn đề gì.\r\n\r\nHàm xử lý ảnh module này dùng là Class Image có sẵn của NukeViet.\r\n`\r\nnew NukeViet\\Files\\Image( $filePath, NV_MAX_WIDTH, NV_MAX_HEIGHT );\r\n`\r\nDo đó cái này mình nghĩ bạn nên tìm 1 môi trường hosting nữa để thử nghiệm cho khách quan."}],"action":{"name":"View Issue","url":"https://github.com/anhyeuviolet/module-photos/issues/40#issuecomment-254374362"}}}

**Comment by anhyeuviolet** [comment]
Cảm ơn bạn đã nhiệt tình.
Về phần hộ trợ từ phía nhà cung cấp, mình nghĩ họ có chút  nhầm lẫn, vì như bạn nói thì upload hoàn chỉnh. Nhưng di chuyển file từ thư mục này sang thư mục khác có vấn đề.
Mình cũng sẽ test lại trên một số môi trường hosting khác.

Một lần nữa cảm ơn bạn !
