### ISSUE TITLE
Hướng dẫn Update lên 4.1 Beta như thế nào vậy anhyeuviolet

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-photos#42]
Update lên 4.1 Beta như thế nào vậy anhyeuviolet. Mình đang dùng 1.3.11

**Comment by anhyeuviolet** [comment]
Bác tham khảo lên 1.3.12 trước:
https://github.com/anhyeuviolet/module-photos/wiki/%5BC%E1%BA%ADp-nh%E1%BA%ADt%5D-C%E1%BA%ADp-nh%E1%BA%ADt-Photos-l%C3%AAn-1.3.12

Sau đó up lên 1.4.01 để chạy với Beta 4.1 cho đẹp.
https://github.com/anhyeuviolet/module-photos/wiki/%5BC%E1%BA%ADp-nh%E1%BA%ADt%5D-C%E1%BA%ADp-nh%E1%BA%ADt-Photos-l%C3%AAn-1.4.01
