### ISSUE TITLE
Lỗi cấu hình block category

### ISSUE THREAD

**Issue by mynukeviet** [anhyeuviolet/module-photos#43]
NukeViet 4.1

Chọn block này nó load không ra cấu hình

![image](https://cloud.githubusercontent.com/assets/6407361/21211606/9e521600-c2b7-11e6-9104-2dd23a9a01f1.png)

**Comment by anhyeuviolet** [comment]
Mình dùng được nè @mynukeviet ơi.
![block](https://cloud.githubusercontent.com/assets/6290970/21211918/46f4ee3e-c2ba-11e6-96f3-61f2db60e10f.PNG)
