### ISSUE TITLE
Không xóa chuyên mục con khi xóa chuyên mục cha

### ISSUE THREAD

**Issue by quocdatit** [anhyeuviolet/module-photos#44]
Khi xóa 1 chuyên mục cha (có cm con bên trong), thì nó vẫn cho xóa, và chỉ xóa chuyên mục cha, còn chuyên mục con vẫn còn trong csdl

**Comment by anhyeuviolet** [comment]
Fixed.
https://github.com/anhyeuviolet/module-photos/commit/f4aa4d1cca07544f66f502de89170fc6604522de
